# Generated by Django 5.2.13 on 2026-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_editora_cidade_editora_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='editora',
            old_name='descricao',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='editora',
            name='site',
            field=models.URLField(blank=True, null=True),
        ),
    ]
